# Copyright (c) 2020 The Plankton Authors.
# All rights reserved.
#
# This source code is derived from UUV Simulator
# (https://github.com/uuvsimulator/uuv_simulator)
# Copyright (c) 2016-2019 The UUV Simulator Authors
# licensed under the Apache license, Version 2.0
# cf. 3rd-party-licenses.txt file in the root directory of this source tree.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


import numpy as np
from rclpy.node import Node
from std_msgs.msg import Float64
import tf_transformations


class FinModel:
    """
    Models a single LAUV fin.

    Calculates its hydrodynamic forces and publishes its angle command.
    """

    def __init__(self, index, pos, quat, topic, node: Node):
        """
        Initialize the FinModel.

        Args
        ----
            index (int): A unique ID for the fin.
            pos (np.array): 3D position vector [x, y, z] relative to base_link.
            quat (np.array): 4D quaternion [x, y, z, w] relative to base_link.
            topic (str): The ROS 2 topic name to publish angle commands to.
            node (rclpy.node.Node): The parent ROS 2 node.

        """
        self.idx = index
        self.pos = pos
        self.quat = quat
        self.topic = topic
        self.node = node

        # Get the full 4x4 transformation matrix from the quaternion
        trans_matrix = tf_transformations.quaternion_matrix(self.quat)

        # Extract the 3x3 rotation matrix
        self.R = trans_matrix[0:3, 0:3]

        # Simplified hydrodynamic coefficients (from reference model)
        self.Cl = 0.1  # Lift coefficient (per radian)
        self.Cd = 0.01  # Drag coefficient

        # --- Create publisher for fin commands ---
        self.pub = self.node.create_publisher(Float64, self.topic, 10)
        self.node.get_logger().info(
            f"Fin {self.idx} initialized, topic: '{self.topic}'"
        )

    def get_force_and_torque(self, alpha, Va):
        """
        Calculate force and torque generated by the fin.

        Args
        ----
            alpha (float): Commanded fin angle in radians.
            Va (float): Vehicle speed (flow speed) in m/s.

        Returns
        -------
            (np.array, np.array): (Force_body_frame, Torque_body_frame)

        """
        if Va < 0.1:  # Avoid issues at zero speed
            return np.zeros(3), np.zeros(3)

        # --- Simplified Hydrodynamic Model ---
        # L = Cl * V^2 * alpha
        # D = Cd * V^2 * (1 + |alpha|)
        L = self.Cl * (Va**2) * alpha
        D = self.Cd * (Va**2) * (1.0 + abs(alpha))

        # --- Force in Fin's Local Frame ---
        # Drag acts along negative X, Lift along positive Y
        F_fin_frame = np.array([-D, L, 0.0])

        # --- Convert Force to Vehicle's Body Frame (base_link) ---
        F_body_frame = self.R @ F_fin_frame

        # --- Calculate Torque in Body Frame ---
        # Torque = r x F
        T_body_frame = np.cross(self.pos, F_body_frame)

        return F_body_frame, T_body_frame

    def publish_command(self, alpha):
        """
        Publish the commanded fin angle.

        Args
        ----
            alpha (float): The fin angle to command (in radians).

        """
        msg = Float64()
        msg.data = float(alpha)
        self.pub.publish(msg)
